version: "3.9"
services:
  spring-webflux:
    build: .
    container_name: spring-webflux
    ports:
      - "8443:8443"
    env_file: .kubernetes.env
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elastic_network
      - jaeger_network
    deploy:
      resources:
        reservations:
          memory: 1G
          cpus: "0.5"
        limits:
          memory: 1G
          cpus: "0.5"

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elastic_network:
    name: elastic_network
    external: true
  jaeger_network:
    name: jaeger_network
    external: true
