encrypt:
  key: EFFbUfV4BB250GznmHdiQ1eYr79q8zSskPAmzVPe/k8=
  salt: 08dbf175cbeb91f3

spring:
  r2dbc:
    primary:
      name: spring_microservice
      url: r2dbc:postgresql://localhost:5432
      username: postgres
      password: 12345678
    readonly:
      name: spring_microservice
      url: r2dbc:postgresql://localhost:5432
      username: postgres
      password: 12345678
  liquibase:
    url: jdbc:postgresql://localhost:5432/spring_microservice
    user: postgres
    password: 12345678
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrapServers: localhost:9092
  redis:
    host: localhost
    port: 6379
  sleuth:
    otel:
      exporter:
        jaeger:
          endpoint: http://localhost:14250
