on:
  push:
    branches:
      - develop
      - release/**
      - staging
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Run JUnit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
#      - name: Execute Gradle Test
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: test --args='--spring.profiles.active=cicd'
